# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Push to docker hub"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "5 3 * * *"
  push:
    branches:
      - "**"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".gitattribute"
      - ".gitignore"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".gitattribute"
      - ".gitignore"

env:
  REPO: lambda3/github-runner-windows

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    strategy:
      fail-fast: false
      matrix:
        year: ["2019", "2022"]
    runs-on: windows-${{ matrix.year }}
    if: ${{ !(github.event_name == 'push' && (github.ref == 'refs/heads/latest' || startsWith(github.ref, 'refs/tags/'))) }}
    outputs:
      push_2019: ${{ steps.push_image.outputs[format('push_{0}', matrix.year)] }}
      push_2022: ${{ steps.push_image.outputs[format('push_{0}', matrix.year)] }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'schedule' }}

      - name: Check out the latest branch
        uses: actions/checkout@v2
        with:
          ref: latest
        if: ${{ github.event_name == 'schedule' }}

      - name: Check if update available
        id: check
        uses: giggio/docker-image-update-checker@v2
        with:
          base-image: mcr.microsoft.com/windows/servercore:ltsc${{ matrix.year }}
          image: ${{ env.REPO }}
          os: windows
          verbose: true
        if: ${{ github.event_name == 'schedule' }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO }}
          flavor: |
            latest=false
          tags: |
            type=sha,prefix=,suffix=-windowsservercore-ltsc${{ matrix.year }}

      - name: Build image
        working-directory: ./runner/
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-Expression "docker build --isolation process --build-arg LTSC_YEAR=${{ matrix.year }} --pull $($env:TAGS.Split("`n") | % { '-t "' + $_ + '"' }) $($env:LABELS.Split("`n") | % { '--label "' + $_ + '"' }) ."
          if ($LASTEXITCODE -ne 0) { throw "Docker build failed." }
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
        if: ${{ success() && (contains(fromJson('["push", "pull_request"]'), github.event_name) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || github.event_name == 'workflow_dispatch') }}

      - name: Docker login
        id: docker_login
        run: |
          $ErrorActionPreference = "Stop"
          docker login -u lambdatres -p $env:DOCKER_PASSWORD
          if ($LASTEXITCODE -ne 0) { throw "Docker login failed." }
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ success() && ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.push && github.event_name == 'workflow_dispatch')) }}

      - name: Push image
        id: push_image
        run: |
          $ErrorActionPreference = "Stop"
          $($env:TAGS.Split("`n") | % {
            docker push $_
            if ($LASTEXITCODE -ne 0) { throw "Docker push failed." }
          })
          Write-Output "::set-output name=push_${{ matrix.year }}::true"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        if: ${{ success() && ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.push && github.event_name == 'workflow_dispatch')) }}

      - name: Docker logout
        run: docker logout
        if: ${{ always() && steps.docker_login.outcome != 'skipped' }}

  push_manifest:
    name: Push Docker manifest to Docker Hub
    runs-on: windows-latest
    needs: push_to_registry
    if: ${{ always() && (needs.push_to_registry.result == 'success' || needs.push_to_registry.result == 'skipped') && ((needs.push_to_registry.outputs.push_2019 == 'true' || needs.push_to_registry.outputs.push_2022 == 'true') || (github.event_name == 'push' && (github.ref == 'refs/heads/latest' || github.ref_type == 'tag'))) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'schedule' }}

      - name: Check out the latest branch
        uses: actions/checkout@v2
        with:
          ref: latest
        if: ${{ github.event_name == 'schedule' }}

      - name: Docker login
        id: docker_login
        run: |
          $ErrorActionPreference = "Stop"
          docker login -u lambdatres -p $env:DOCKER_PASSWORD
          if ($LASTEXITCODE -ne 0) { throw "Docker login failed." }
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      - name: Push manifest
        run: |
          $env:DOCKER_CLI_EXPERIMENTAL='enabled'
          $sha = $(git rev-parse --short HEAD)
          docker manifest create ${{ steps.meta.outputs.tags }} --amend ${env:REPO}:$sha-windowsservercore-ltsc2019 --amend ${env:REPO}:$sha-windowsservercore-ltsc2022
          docker manifest push ${{ steps.meta.outputs.tags }}
          docker manifest create ${env:REPO}:$sha --amend ${env:REPO}:$sha-windowsservercore-ltsc2019 --amend ${env:REPO}:$sha-windowsservercore-ltsc2022
          docker manifest push ${env:REPO}:$sha
      - name: Docker logout
        run: docker logout
        if: ${{ always() && steps.docker_login.outcome != 'skipped' }}
